//TRY-CATCH

const numero1 = 100
const numero3 = 400

console.log(numero1)
try{
    console.log(numero2)

}catch (error){
    console.log(error)
}

console.log(numero3)



